name: Python application

on:
  workflow_dispatch:
  schedule: 
    - cron: "45 18 * * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update file
      env:
        SPOTIPY_CLIENT_ID: ${{secrets.SPOTIPY_CLIENT_ID}}
        SPOTIPY_CLIENT_SECRET: ${{secrets.SPOTIPY_CLIENT_SECRET}}
      run: |
        python playlist_tracker.py
    - name: Commit back
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automated update
        
